### ISSUE TITLE
Remove the Bittrex minimum order size check when adding coins to the index.

### ISSUE THREAD

**Issue by r4stl1n** [R4stl1n/condex#13]
Fringe case was found when trying to convert a preexisting index from coincube to condex. If the BTC value is low enough adding multiple indexed coins can cause condex to not allow adding a coin to the index. 

We should remove this check to allow easy migration from coincube to condex. However this check should be reran before starting the index to ensure that all coins meet the minimum requirements.

**Comment by cribbstechnologies** [comment]
This check can be removed everywhere *except* during re-balance operations. The re-balance activity already has this check in there and won't post the trade if the minimum isn't met.
