### ISSUE TITLE
Unrealized gain calculated incorrectly.

### ISSUE THREAD

**Issue by r4stl1n** [R4stl1n/condex#2]
The unrealized gain is currently being calculated incorrectly has the values are always tied to equal 100%. This is incorrect has they should be independently calculated against the individual coins gains and losses.

**Comment by cribbstechnologies** [comment]
To clarify the unrealized gain should be (current - cost)/cost. Correct?

**Comment by notnight** [comment]
Correct.
Unrealized gain is ((current - cost)/cost) * 100 to return a percentage.

**Comment by cribbstechnologies** [comment]
When does realized gain come into play? When coins are sold?

**Comment by r4stl1n** [comment]
Just keep in mind this isn't just a visual issue there might be places where this is used within the automated tasks (Trade Engine).

Also yes realized gain is only when coins are sold.

**Comment by notnight** [comment]
Yes, realized is once you have sold the coins at a profit.

**Comment by cribbstechnologies** [comment]
realized all this was unneeded
